# -*- coding: utf-8 -*-
"""india_covid_19_info.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIt1EjCV88ioRVPrakTXqirqzETIu-af

**MOUNTING  GOOGLE DRIVE**
"""
import pandas as pd
from time import *;

sleep(10)

"""# **IMPORTING REQUESTS PACKAGE TO READ JSON**"""

import requests as rq

r = rq.get("https://api.covid19india.org/state_district_wise.json")
sleep(30)

print(r.status_code)

from pandas import DataFrame as df

"""# **Testting Json File**"""

an = df(r.json()["Andaman and Nicobar Islands"]["districtData"])

ap = df(r.json()["Andhra Pradesh"]["districtData"])
print(ap)

"""# **Name of all State of India**"""

liststate = ["Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Delhi", "Dadra and Nagar Haveli and Daman and Diu", "Goa",
             "Gujarat", "Himachal Pradesh", "Haryana", "Jharkhand", "Jammu and Kashmir", "Karnataka", "Kerala",
             "Ladakh", "Lakshadweep", "Maharashtra", "Meghalaya", "Manipur", "Madhya Pradesh", "Mizoram", "Nagaland",
             "Odisha", "Punjab", "Puducherry", "Rajasthan", "Sikkim", "Telangana", "Tamil Nadu", "Tripura",
             "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Andhra Pradesh",
             "Arunachal Pradesh"]

print(len(liststate))

"""# Getting Names District (740) as per 2020
# Few District are removed from csv due to error in json
"""

listdis = []
j = 0
for i in liststate:
    dislist = []
    temp = df(r.json()[i]["districtData"])
    for x in temp.head():
        dislist.append(x)
    listdis.append(dislist)
print(listdis)

"""# **Segregating District StateWise To ploat Charts and Graphs**

>
"""

dicdis = df(listdis)
# print(dicdis)
assam = dicdis.loc[0]
assams = []
for b in assam:
    if b is not None:
        assams.append(b)
print(assams)

"""# **Getting District Wise Number of Cases Using StateName &union territories**"""

assamss = df(r.json()["Assam"]["districtData"])
assamactive = []
assamconfirmed = []
assamdeceased = []
assamrecovered = []
for i in assams:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        assamactive.append(assamss[i]["active"])
        assamconfirmed.append(assamss[i]["confirmed"])
        assamdeceased.append(assamss[i]["deceased"])
        assamrecovered.append(assamss[i]["recovered"])
assam_act = sum(assamactive)
assam_con = sum(assamconfirmed)
assam_dec = sum(assamdeceased)
assam_rec = sum(assamrecovered)

"""**Removing Unwanted Names from Json eg-Airport Quarantine,Other state and ect**"""

bihar = dicdis.loc[1]
bihars = []
for b in bihar:
    if b is not None:
        bihars.append(b)

"""# Creating List StateWise 


```

> biharactive- To get all the cases district Wise
> bihars-To get all district Name (1d )list
# >bihars_act-list to calculate total sum of active cases to plot graphs
```
"""

biharss = df(r.json()["Bihar"]["districtData"])
biharactive = []
biharconfirmed = []
bihardeceased = []
biharrecovered = []
for i in bihars:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        biharactive.append(biharss[i]["active"])
        biharconfirmed.append(biharss[i]["confirmed"])
        bihardeceased.append(biharss[i]["deceased"])
        biharrecovered.append(biharss[i]["recovered"])
bihar_act = sum(biharactive)
bihar_con = sum(biharconfirmed)
bihar_dec = sum(bihardeceased)
bihar_rec = sum(bihardeceased)

Chandigarh = dicdis.loc[2]
Chandigarhs = []
for b in Chandigarh:
    if b is not None:
        Chandigarhs.append(b)

Chandigarhss = df(r.json()["Chandigarh"]["districtData"])
Chandigarhactive = []
Chandigarhconfirmed = []
Chandigarhdeceased = []
Chandigarhrecovered = []
for i in Chandigarhs:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Chandigarhactive.append(Chandigarhss[i]['active'])
        Chandigarhconfirmed.append(Chandigarhss[i]["confirmed"])
        Chandigarhdeceased.append(Chandigarhss[i]["deceased"])
        Chandigarhrecovered.append(Chandigarhss[i]["recovered"])
Chandigarh_act = sum(Chandigarhactive)
Chandigarh_con = sum(Chandigarhconfirmed)
Chandigarh_dec = sum(Chandigarhdeceased)
Chandigarh_rec = sum(Chandigarhrecovered)

Chhattisgarh = dicdis.loc[3]
Chhattisgarhs = []
for ch in Chhattisgarh:
    if ch is not None:
        Chhattisgarhs.append(ch)

Chhattisgarhss = df(r.json()["Chhattisgarh"]["districtData"])
Chhattisgarhactive = []
Chhattisgarhconfirmed = []
Chhattisgarhdeceased = []
Chhattisgarhrecovered = []
for i in Chhattisgarhs:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Chhattisgarhactive.append(Chhattisgarhss[i]["active"])
        Chhattisgarhconfirmed.append(Chhattisgarhss[i]["confirmed"])
        Chhattisgarhdeceased.append(Chhattisgarhss[i]["deceased"])
        Chhattisgarhrecovered.append(Chhattisgarhss[i]["recovered"])
Chhattisgarh_act = sum(Chhattisgarhactive)
Chhattisgarh_con = sum(Chhattisgarhconfirmed)
Chhattisgarh_dec = sum(Chhattisgarhdeceased)
Chhattisgarh_rec = sum(Chhattisgarhrecovered)

Delhi = dicdis.loc[4]
Delhis = []
for ch in Delhi:
    if ch is not None:
        Delhis.append(ch)
Delhiss = df(r.json()["Delhi"]["districtData"])
Delhiactive = []
Delhiconfirmed = []
Delhideceased = []
Delhirecovered = []
for i in Delhis:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:

        Delhiactive.append(Delhiss[i]["active"])
        Delhiconfirmed.append(Delhiss[i]["confirmed"])
        Delhideceased.append(Delhiss[i]["deceased"])
        Delhirecovered.append(Delhiss[i]["recovered"])
Delhi_act = sum(Delhiactive)
Delhi_con = sum(Delhiconfirmed)
Delhi_dec = sum(Delhideceased)
Delhi_rec = sum(Delhirecovered)

Dadra_and_Nagar_Haveli_and_Daman_and_Diu = dicdis.loc[5]
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_s = []
for ch in Dadra_and_Nagar_Haveli_and_Daman_and_Diu:
    if ch is not None:
        Dadra_and_Nagar_Haveli_and_Daman_and_Diu_s.append(ch)
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_ss = df(r.json()["Dadra and Nagar Haveli and Daman and Diu"]["districtData"])
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_active = []
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_confirmed = []
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_deceased = []
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_recovered = []
for i in Dadra_and_Nagar_Haveli_and_Daman_and_Diu_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Dadra_and_Nagar_Haveli_and_Daman_and_Diu_active.append(Dadra_and_Nagar_Haveli_and_Daman_and_Diu_ss[i]["active"])
        Dadra_and_Nagar_Haveli_and_Daman_and_Diu_confirmed.append(
            Dadra_and_Nagar_Haveli_and_Daman_and_Diu_ss[i]["confirmed"])
        Dadra_and_Nagar_Haveli_and_Daman_and_Diu_deceased.append(
            Dadra_and_Nagar_Haveli_and_Daman_and_Diu_ss[i]["deceased"])
        Dadra_and_Nagar_Haveli_and_Daman_and_Diu_recovered.append(
            Dadra_and_Nagar_Haveli_and_Daman_and_Diu_ss[i]["recovered"])
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_act = sum(Dadra_and_Nagar_Haveli_and_Daman_and_Diu_active)
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_con = sum(Dadra_and_Nagar_Haveli_and_Daman_and_Diu_confirmed)
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_dec = sum(Dadra_and_Nagar_Haveli_and_Daman_and_Diu_deceased)
Dadra_and_Nagar_Haveli_and_Daman_and_Diu_rec = sum(Dadra_and_Nagar_Haveli_and_Daman_and_Diu_recovered)

Goa = dicdis.loc[6]
Goa_s = []
for ch in Goa:
    if ch is not None:
        Goa_s.append(ch)
Goa_ss = df(r.json()["Goa"]["districtData"])
Goa_active = []
Goa_confirmed = []
Goa_deceased = []
Goa_recovered = []
for i in Goa_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Goa_active.append(Goa_ss[i]["active"])
        Goa_confirmed.append(Goa_ss[i]["confirmed"])
        Goa_deceased.append(Goa_ss[i]["deceased"])
        Goa_recovered.append(Goa_ss[i]["recovered"])
Goa_act = sum(Goa_active)
Goa_con = sum(Goa_confirmed)
Goa_dec = sum(Goa_deceased)
Goa_rec = sum(Goa_recovered)

Gujarat = dicdis.loc[7]
Gujarat_s = []
for ch in Gujarat:
    if ch is not None:
        Gujarat_s.append(ch)
Gujarat_ss = df(r.json()["Gujarat"]["districtData"])
Gujarat_active = []
Gujarat_confirmed = []
Gujarat_deceased = []
Gujarat_recovered = []
for i in Gujarat_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Gujarat_active.append(Gujarat_ss[i]["active"])
        Gujarat_confirmed.append(Gujarat_ss[i]["confirmed"])
        Gujarat_deceased.append(Gujarat_ss[i]["deceased"])
        Gujarat_recovered.append(Gujarat_ss[i]["recovered"])
Gujarat_act = sum(Gujarat_active)
Gujarat_con = sum(Gujarat_confirmed)
Gujarat_dec = sum(Gujarat_deceased)
Gujarat_rec = sum(Gujarat_recovered)

Himachal_Pradesh = dicdis.loc[8]
Himachal_Pradesh_s = []
for ch in Himachal_Pradesh:
    if ch is not None:
        Himachal_Pradesh_s.append(ch)
Himachal_Pradesh_ss = df(r.json()["Himachal Pradesh"]["districtData"])
Himachal_Pradesh_active = []
Himachal_Pradesh_confirmed = []
Himachal_Pradesh_deceased = []
Himachal_Pradesh_recovered = []
for i in Himachal_Pradesh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Himachal_Pradesh_active.append(Himachal_Pradesh_ss[i]["active"])
        Himachal_Pradesh_confirmed.append(Himachal_Pradesh_ss[i]["confirmed"])
        Himachal_Pradesh_deceased.append(Himachal_Pradesh_ss[i]["deceased"])
        Himachal_Pradesh_recovered.append(Himachal_Pradesh_ss[i]["recovered"])
Himachal_Pradesh_act = sum(Himachal_Pradesh_active)
Himachal_Pradesh_con = sum(Himachal_Pradesh_confirmed)
Himachal_Pradesh_dec = sum(Himachal_Pradesh_deceased)
Himachal_Pradesh_rec = sum(Himachal_Pradesh_recovered)

Haryana = dicdis.loc[9]
Haryana_s = []
for ch in Haryana:
    if ch is not None:
        Haryana_s.append(ch)
Haryana_ss = df(r.json()["Haryana"]["districtData"])
Haryana_active = []
Haryana_confirmed = []
Haryana_deceased = []
Haryana_recovered = []
for i in Haryana_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Haryana_active.append(Haryana_ss[i]["active"])
        Haryana_confirmed.append(Haryana_ss[i]["confirmed"])
        Haryana_deceased.append(Haryana_ss[i]["deceased"])
        Haryana_recovered.append(Haryana_ss[i]["recovered"])
Haryana_act = sum(Haryana_active)
Haryana_con = sum(Haryana_confirmed)
Haryana_dec = sum(Haryana_deceased)
Haryana_rec = sum(Haryana_recovered)

Haryana = dicdis.loc[9]
Haryana_s = []
for ch in Haryana:
    if ch is not None:
        Haryana_s.append(ch)
Haryana_ss = df(r.json()["Haryana"]["districtData"])
Haryana_active = []
Haryana_confirmed = []
Haryana_deceased = []
Haryana_recovered = []
for i in Haryana_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Haryana_active.append(Haryana_ss[i]["active"])
        Haryana_confirmed.append(Haryana_ss[i]["confirmed"])
        Haryana_deceased.append(Haryana_ss[i]["deceased"])
        Haryana_recovered.append(Haryana_ss[i]["recovered"])
Haryana_act = sum(Haryana_active)
Haryana_con = sum(Haryana_confirmed)
Haryana_dec = sum(Haryana_deceased)
Haryana_rec = sum(Haryana_recovered)

Jharkhand = dicdis.loc[10]
Jharkhand_s = []
for ch in Jharkhand:
    if ch is not None:
        Jharkhand_s.append(ch)
Jharkhand_ss = df(r.json()["Jharkhand"]["districtData"])
Jharkhand_active = []
Jharkhand_confirmed = []
Jharkhand_deceased = []
Jharkhand_recovered = []
for i in Jharkhand_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Jharkhand_active.append(Jharkhand_ss[i]["active"])
        Jharkhand_confirmed.append(Jharkhand_ss[i]["confirmed"])
        Jharkhand_deceased.append(Jharkhand_ss[i]["deceased"])
        Jharkhand_recovered.append(Jharkhand_ss[i]["recovered"])
Jharkhand_act = sum(Jharkhand_active)
Jharkhand_con = sum(Jharkhand_confirmed)
Jharkhand_dec = sum(Jharkhand_deceased)
Jharkhand_rec = sum(Jharkhand_recovered)

Jammu_and_Kashmir = dicdis.loc[11]
Jammu_and_Kashmir_s = []
for ch in Jammu_and_Kashmir:
    if ch is not None:
        Jammu_and_Kashmir_s.append(ch)
Jammu_and_Kashmir_ss = df(r.json()["Jammu and Kashmir"]["districtData"])
Jammu_and_Kashmir_active = []
Jammu_and_Kashmir_confirmed = []
Jammu_and_Kashmir_deceased = []
Jammu_and_Kashmir_recovered = []
for i in Jammu_and_Kashmir_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Jammu_and_Kashmir_active.append(Jammu_and_Kashmir_ss[i]["active"])
        Jammu_and_Kashmir_confirmed.append(Jammu_and_Kashmir_ss[i]["confirmed"])
        Jammu_and_Kashmir_deceased.append(Jammu_and_Kashmir_ss[i]["deceased"])
        Jammu_and_Kashmir_recovered.append(Jammu_and_Kashmir_ss[i]["recovered"])
Jammu_and_Kashmir_act = sum(Jammu_and_Kashmir_active)
Jammu_and_Kashmir_con = sum(Jammu_and_Kashmir_confirmed)
Jammu_and_Kashmir_dec = sum(Jammu_and_Kashmir_deceased)
Jammu_and_Kashmir_rec = sum(Jammu_and_Kashmir_recovered)

Karnataka = dicdis.loc[12]
Karnataka_s = []
for ch in Karnataka:
    if ch is not None:
        Karnataka_s.append(ch)
Karnataka_ss = df(r.json()["Karnataka"]["districtData"])
Karnataka_active = []
Karnataka_confirmed = []
Karnataka_deceased = []
Karnataka_recovered = []
for i in Karnataka_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Karnataka_active.append(Karnataka_ss[i]["active"])
        Karnataka_confirmed.append(Karnataka_ss[i]["confirmed"])
        Karnataka_deceased.append(Karnataka_ss[i]["deceased"])
        Karnataka_recovered.append(Karnataka_ss[i]["recovered"])
Karnataka_act = sum(Karnataka_active)
Karnataka_con = sum(Karnataka_confirmed)
Karnataka_dec = sum(Karnataka_deceased)
Karnataka_rec = sum(Karnataka_recovered)

Kerala = dicdis.loc[13]
Kerala_s = []
for ch in Kerala:
    if ch is not None:
        Kerala_s.append(ch)
Kerala_ss = df(r.json()["Kerala"]["districtData"])
Kerala_active = []
Kerala_confirmed = []
Kerala_deceased = []
Kerala_recovered = []
for i in Kerala_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Kerala_active.append(Kerala_ss[i]["active"])
        Kerala_confirmed.append(Kerala_ss[i]["confirmed"])
        Kerala_deceased.append(Kerala_ss[i]["deceased"])
        Kerala_recovered.append(Kerala_ss[i]["recovered"])
Kerala_act = sum(Kerala_active)
Kerala_con = sum(Kerala_confirmed)
Kerala_dec = sum(Kerala_deceased)
Kerala_rec = sum(Kerala_recovered)

Ladakh = dicdis.loc[14]
Ladakh_s = []
for ch in Ladakh:
    if ch is not None:
        Ladakh_s.append(ch)
Ladakh_ss = df(r.json()["Ladakh"]["districtData"])
Ladakh_active = []
Ladakh_confirmed = []
Ladakh_deceased = []
Ladakh_recovered = []
for i in Ladakh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Ladakh_active.append(Ladakh_ss[i]["active"])
        Ladakh_confirmed.append(Ladakh_ss[i]["confirmed"])
        Ladakh_deceased.append(Ladakh_ss[i]["deceased"])
        Ladakh_recovered.append(Ladakh_ss[i]["recovered"])
Ladakh_act = sum(Ladakh_active)
Ladakh_con = sum(Ladakh_confirmed)
Ladakh_dec = sum(Ladakh_deceased)
Ladakh_rec = sum(Ladakh_recovered)

Lakshadweep = dicdis.loc[15]
Lakshadweep_s = []
for ch in Lakshadweep:
    if ch is not None:
        Lakshadweep_s.append(ch)

Lakshadweep_ss = df(r.json()["Lakshadweep"]["districtData"])
Lakshadweep_active = []
Lakshadweep_confirmed = []
Lakshadweep_deceased = []
Lakshadweep_recovered = []
for i in Lakshadweep_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Lakshadweep_active.append(Lakshadweep_ss[i]["active"])
        Lakshadweep_confirmed.append(Lakshadweep_ss[i]["confirmed"])
        Lakshadweep_deceased.append(Lakshadweep_ss[i]["deceased"])
        Lakshadweep_recovered.append(Lakshadweep_ss[i]["recovered"])
Lakshadweep_act = sum(Lakshadweep_active)
Lakshadweep_con = sum(Lakshadweep_confirmed)
Lakshadweep_dec = sum(Lakshadweep_deceased)
Lakshadweep_rec = sum(Lakshadweep_recovered)

Maharashtra = dicdis.loc[16]
Maharashtra_s = []
for ch in Maharashtra:
    if ch is not None:
        Maharashtra_s.append(ch)
Maharashtra_ss = df(r.json()["Maharashtra"]["districtData"])
Maharashtra_active = []
Maharashtra_confirmed = []
Maharashtra_deceased = []
Maharashtra_recovered = []
for i in Maharashtra_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Maharashtra_active.append(Maharashtra_ss[i]["active"])
        Maharashtra_confirmed.append(Maharashtra_ss[i]["confirmed"])
        Maharashtra_deceased.append(Maharashtra_ss[i]["deceased"])
        Maharashtra_recovered.append(Maharashtra_ss[i]["recovered"])
Maharashtra_act = sum(Maharashtra_active)
Maharashtra_con = sum(Maharashtra_confirmed)
Maharashtra_dec = sum(Maharashtra_deceased)
Maharashtra_rec = sum(Maharashtra_recovered)

Meghalaya = dicdis.loc[17]
Meghalaya_s = []
for ch in Meghalaya:
    if ch is not None:
        Meghalaya_s.append(ch)
Meghalaya_ss = df(r.json()["Meghalaya"]["districtData"])
Meghalaya_active = []
Meghalaya_confirmed = []
Meghalaya_deceased = []
Meghalaya_recovered = []
for i in Meghalaya_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Meghalaya_active.append(Meghalaya_ss[i]["active"])
        Meghalaya_confirmed.append(Meghalaya_ss[i]["confirmed"])
        Meghalaya_deceased.append(Meghalaya_ss[i]["deceased"])
        Meghalaya_recovered.append(Meghalaya_ss[i]["recovered"])
Meghalaya_act = sum(Meghalaya_active)
Meghalaya_con = sum(Meghalaya_confirmed)
Meghalaya_dec = sum(Meghalaya_deceased)
Meghalaya_rec = sum(Meghalaya_recovered)

Manipur = dicdis.loc[18]
Manipur_s = []
for ch in Manipur:
    if ch is not None:
        Manipur_s.append(ch)
Manipur_ss = df(r.json()["Manipur"]["districtData"])
Manipur_active = []
Manipur_confirmed = []
Manipur_deceased = []
Manipur_recovered = []
for i in Manipur_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Manipur_active.append(Manipur_ss[i]["active"])
        Manipur_confirmed.append(Manipur_ss[i]["confirmed"])
        Manipur_deceased.append(Manipur_ss[i]["deceased"])
        Manipur_recovered.append(Manipur_ss[i]["recovered"])
Manipur_act = sum(Manipur_active)
Manipur_con = sum(Manipur_confirmed)
Manipur_dec = sum(Manipur_deceased)
Manipur_rec = sum(Manipur_recovered)

Madhya_Pradesh = dicdis.loc[19]
Madhya_Pradesh_s = []
for ch in Madhya_Pradesh:
    if ch is not None:
        Madhya_Pradesh_s.append(ch)
Madhya_Pradesh_ss = df(r.json()["Madhya Pradesh"]["districtData"])
Madhya_Pradesh_active = []
Madhya_Pradesh_confirmed = []
Madhya_Pradesh_deceased = []
Madhya_Pradesh_recovered = []
for i in Madhya_Pradesh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Madhya_Pradesh_active.append(Madhya_Pradesh_ss[i]["active"])
        Madhya_Pradesh_confirmed.append(Madhya_Pradesh_ss[i]["confirmed"])
        Madhya_Pradesh_deceased.append(Madhya_Pradesh_ss[i]["deceased"])
        Madhya_Pradesh_recovered.append(Madhya_Pradesh_ss[i]["recovered"])
Madhya_Pradesh_act = sum(Madhya_Pradesh_active)
Madhya_Pradesh_con = sum(Madhya_Pradesh_confirmed)
Madhya_Pradesh_dec = sum(Madhya_Pradesh_deceased)
Madhya_Pradesh_rec = sum(Madhya_Pradesh_recovered)

Mizoram = dicdis.loc[20]
Mizoram_s = []
for ch in Mizoram:
    if ch is not None:
        Mizoram_s.append(ch)
Mizoram_ss = df(r.json()["Mizoram"]["districtData"])
Mizoram_active = []
Mizoram_confirmed = []
Mizoram_deceased = []
Mizoram_recovered = []
for i in Mizoram_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Mizoram_active.append(Mizoram_ss[i]["active"])
        Mizoram_confirmed.append(Mizoram_ss[i]["confirmed"])
        Mizoram_deceased.append(Mizoram_ss[i]["deceased"])
        Mizoram_recovered.append(Mizoram_ss[i]["recovered"])
Mizoram_act = sum(Mizoram_active)
Mizoram_con = sum(Mizoram_confirmed)
Mizoram_dec = sum(Mizoram_deceased)
Mizoram_rec = sum(Mizoram_recovered)

Nagaland = dicdis.loc[21]
Nagaland_s = []
for ch in Nagaland:
    if ch is not None:
        Nagaland_s.append(ch)
Nagaland_ss = df(r.json()["Nagaland"]["districtData"])
Nagaland_active = []
Nagaland_confirmed = []
Nagaland_deceased = []
Nagaland_recovered = []
for i in Nagaland_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Nagaland_active.append(Nagaland_ss[i]["active"])
        Nagaland_confirmed.append(Nagaland_ss[i]["confirmed"])
        Nagaland_deceased.append(Nagaland_ss[i]["deceased"])
        Nagaland_recovered.append(Nagaland_ss[i]["recovered"])
Nagaland_act = sum(Nagaland_active)
Nagaland_con = sum(Nagaland_confirmed)
Nagaland_dec = sum(Nagaland_deceased)
Nagaland_rec = sum(Nagaland_recovered)

Odisha = dicdis.loc[22]
Odisha_s = []
for ch in Odisha:
    if ch is not None:
        Odisha_s.append(ch)
Odisha_ss = df(r.json()["Odisha"]["districtData"])
Odisha_active = []
Odisha_confirmed = []
Odisha_deceased = []
Odisha_recovered = []
for i in Odisha_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine " or i == "Others"):
        continue
    else:
        Odisha_active.append(Odisha_ss[i]["active"])
        Odisha_confirmed.append(Odisha_ss[i]["confirmed"])
        Odisha_deceased.append(Odisha_ss[i]["deceased"])
        Odisha_recovered.append(Odisha_ss[i]["recovered"])
Odisha_act = sum(Odisha_active)
Odisha_con = sum(Odisha_confirmed)
Odisha_dec = sum(Odisha_deceased)
Odisha_rec = sum(Odisha_recovered)

Punjab = dicdis.loc[23]
Punjab_s = []
for ch in Punjab:
    if ch is not None:
        Punjab_s.append(ch)
Punjab_ss = df(r.json()["Punjab"]["districtData"])
Punjab_active = []
Punjab_confirmed = []
Punjab_deceased = []
Punjab_recovered = []
for i in Punjab_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Punjab_active.append(Punjab_ss[i]["active"])
        Punjab_confirmed.append(Punjab_ss[i]["confirmed"])
        Punjab_deceased.append(Punjab_ss[i]["deceased"])
        Punjab_recovered.append(Punjab_ss[i]["recovered"])
Punjab_act = sum(Punjab_active)
Punjab_con = sum(Punjab_confirmed)
Punjab_dec = sum(Punjab_deceased)
Punjab_rec = sum(Punjab_recovered)

Puducherry = dicdis.loc[24]
Puducherry_s = []
for ch in Puducherry:
    if ch is not None:
        Puducherry_s.append(ch)
Puducherry_ss = df(r.json()["Puducherry"]["districtData"])
Puducherry_active = []
Puducherry_confirmed = []
Puducherry_deceased = []
Puducherry_recovered = []
for i in Puducherry_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Puducherry_active.append(Puducherry_ss[i]["active"])
        Puducherry_confirmed.append(Puducherry_ss[i]["confirmed"])
        Puducherry_deceased.append(Puducherry_ss[i]["deceased"])
        Puducherry_recovered.append(Puducherry_ss[i]["recovered"])
Puducherry_act = sum(Puducherry_active)
Puducherry_con = sum(Puducherry_confirmed)
Puducherry_dec = sum(Puducherry_deceased)
Puducherry_rec = sum(Puducherry_recovered)

Rajasthan = dicdis.loc[25]
Rajasthan_s = []
for ch in Rajasthan:
    if ch is not None:
        Rajasthan_s.append(ch)

Rajasthan_ss = df(r.json()["Rajasthan"]["districtData"])
Rajasthan_active = []
Rajasthan_confirmed = []
Rajasthan_deceased = []
Rajasthan_recovered = []
for i in Rajasthan_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Rajasthan_active.append(Rajasthan_ss[i]["active"])
        Rajasthan_confirmed.append(Rajasthan_ss[i]["confirmed"])
        Rajasthan_deceased.append(Rajasthan_ss[i]["deceased"])
        Rajasthan_recovered.append(Rajasthan_ss[i]["recovered"])
Rajasthan_act = sum(Rajasthan_active)
Rajasthan_con = sum(Rajasthan_confirmed)
Rajasthan_dec = sum(Rajasthan_deceased)
Rajasthan_rec = sum(Rajasthan_recovered)

Sikkim = dicdis.loc[26]
Sikkim_s = []
for ch in Sikkim:
    if ch is not None:
        Sikkim_s.append(ch)
Sikkim_ss = df(r.json()["Sikkim"]["districtData"])
Sikkim_active = []
Sikkim_confirmed = []
Sikkim_deceased = []
Sikkim_recovered = []
for i in Sikkim_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Sikkim_active.append(Sikkim_ss[i]["active"])
        Sikkim_confirmed.append(Sikkim_ss[i]["confirmed"])
        Sikkim_deceased.append(Sikkim_ss[i]["deceased"])
        Sikkim_recovered.append(Sikkim_ss[i]["recovered"])
Sikkim_act = sum(Sikkim_active)
Sikkim_con = sum(Sikkim_confirmed)
Sikkim_dec = sum(Sikkim_deceased)
Sikkim_rec = sum(Sikkim_recovered)

Telangana = dicdis.loc[27]
Telangana_s = []
for ch in Telangana:
    if ch is not None:
        Telangana_s.append(ch)
Telangana_ss = df(r.json()["Telangana"]["districtData"])
Telangana_active = []
Telangana_confirmed = []
Telangana_deceased = []
Telangana_recovered = []
for i in Telangana_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Telangana_active.append(Telangana_ss[i]["active"])
        Telangana_confirmed.append(Telangana_ss[i]["confirmed"])
        Telangana_deceased.append(Telangana_ss[i]["deceased"])
        Telangana_recovered.append(Telangana_ss[i]["recovered"])
Telangana_act = sum(Telangana_active)
Telangana_con = sum(Telangana_confirmed)
Telangana_dec = sum(Telangana_deceased)
Telangana_rec = sum(Telangana_recovered)

Tamil_Nadu = dicdis.loc[28]
Tamil_Nadu_s = []
for ch in Tamil_Nadu:
    if ch is not None:
        Tamil_Nadu_s.append(ch)
Tamil_Nadu_ss = df(r.json()["Tamil Nadu"]["districtData"])
Tamil_Nadu_active = []
Tamil_Nadu_confirmed = []
Tamil_Nadu_deceased = []
Tamil_Nadu_recovered = []
for i in Tamil_Nadu_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Tamil_Nadu_active.append(Tamil_Nadu_ss[i]["active"])
        Tamil_Nadu_confirmed.append(Tamil_Nadu_ss[i]["confirmed"])
        Tamil_Nadu_deceased.append(Tamil_Nadu_ss[i]["deceased"])
        Tamil_Nadu_recovered.append(Tamil_Nadu_ss[i]["recovered"])
Tamil_Nadu_act = sum(Tamil_Nadu_active)
Tamil_Nadu_con = sum(Tamil_Nadu_confirmed)
Tamil_Nadu_dec = sum(Tamil_Nadu_deceased)
Tamil_Nadu_rec = sum(Tamil_Nadu_recovered)

Tripura = dicdis.loc[29]
Tripura_s = []
for ch in Tripura:
    if ch is not None:
        Tripura_s.append(ch)
Tripura_ss = df(r.json()["Tripura"]["districtData"])
Tripura_active = []
Tripura_confirmed = []
Tripura_deceased = []
Tripura_recovered = []
for i in Tripura_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Tripura_active.append(Tripura_ss[i]["active"])
        Tripura_confirmed.append(Tripura_ss[i]["confirmed"])
        Tripura_deceased.append(Tripura_ss[i]["deceased"])
        Tripura_recovered.append(Tripura_ss[i]["recovered"])
Tripura_act = sum(Tripura_active)
Tripura_con = sum(Tripura_confirmed)
Tripura_dec = sum(Tripura_deceased)
Tripura_rec = sum(Tripura_recovered)

Uttar_Pradesh = dicdis.loc[30]
Uttar_Pradesh_s = []
for ch in Uttar_Pradesh:
    if ch is not None:
        Uttar_Pradesh_s.append(ch)
Uttar_Pradesh_ss = df(r.json()["Uttar Pradesh"]["districtData"])
Uttar_Pradesh_active = []
Uttar_Pradesh_confirmed = []
Uttar_Pradesh_deceased = []
Uttar_Pradesh_recovered = []
for i in Uttar_Pradesh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Uttar_Pradesh_active.append(Uttar_Pradesh_ss[i]["active"])
        Uttar_Pradesh_confirmed.append(Uttar_Pradesh_ss[i]["confirmed"])
        Uttar_Pradesh_deceased.append(Uttar_Pradesh_ss[i]["deceased"])
        Uttar_Pradesh_recovered.append(Uttar_Pradesh_ss[i]["recovered"])
Uttar_Pradesh_act = sum(Uttar_Pradesh_active)
Uttar_Pradesh_con = sum(Uttar_Pradesh_confirmed)
Uttar_Pradesh_dec = sum(Uttar_Pradesh_deceased)
Uttar_Pradesh_rec = sum(Uttar_Pradesh_recovered)

Uttarakhand = dicdis.loc[31]
Uttarakhand_s = []
for ch in Uttarakhand:
    if ch is not None:
        Uttarakhand_s.append(ch)
Uttarakhand_ss = df(r.json()["Uttarakhand"]["districtData"])
Uttarakhand_active = []
Uttarakhand_confirmed = []
Uttarakhand_deceased = []
Uttarakhand_recovered = []
for i in Uttarakhand_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Uttarakhand_active.append(Uttarakhand_ss[i]["active"])
        Uttarakhand_confirmed.append(Uttarakhand_ss[i]["confirmed"])
        Uttarakhand_deceased.append(Uttarakhand_ss[i]["deceased"])
        Uttarakhand_recovered.append(Uttarakhand_ss[i]["recovered"])
Uttarakhand_act = sum(Uttarakhand_active)
Uttarakhand_con = sum(Uttarakhand_confirmed)
Uttarakhand_dec = sum(Uttarakhand_deceased)
Uttarakhand_rec = sum(Uttarakhand_recovered)

West_Bengal = dicdis.loc[32]
West_Bengal_s = []
for ch in West_Bengal:
    if ch is not None:
        West_Bengal_s.append(ch)
West_Bengal_ss = df(r.json()["West Bengal"]["districtData"])
West_Bengal_active = []
West_Bengal_confirmed = []
West_Bengal_deceased = []
West_Bengal_recovered = []
for i in West_Bengal_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        West_Bengal_active.append(West_Bengal_ss[i]["active"])
        West_Bengal_confirmed.append(West_Bengal_ss[i]["confirmed"])
        West_Bengal_deceased.append(West_Bengal_ss[i]["deceased"])
        West_Bengal_recovered.append(West_Bengal_ss[i]["recovered"])
West_Bengal_act = sum(West_Bengal_active)
West_Bengal_con = sum(West_Bengal_confirmed)
West_Bengal_dec = sum(West_Bengal_deceased)
West_Bengal_rec = sum(West_Bengal_recovered)

Andaman_and_Nicobar_Islands = dicdis.loc[33]
Andaman_and_Nicobar_Islands_s = []
for ch in Andaman_and_Nicobar_Islands:
    if ch is not None:
        Andaman_and_Nicobar_Islands_s.append(ch)
Andaman_and_Nicobar_Islands_ss = df(r.json()["Andaman and Nicobar Islands"]["districtData"])
Andaman_and_Nicobar_Islands_active = []
Andaman_and_Nicobar_Islands_confirmed = []
Andaman_and_Nicobar_Islands_deceased = []
Andaman_and_Nicobar_Islands_recovered = []
for i in Andaman_and_Nicobar_Islands_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine" or i == "Nicobars"):
        continue
    else:
        Andaman_and_Nicobar_Islands_active.append(Andaman_and_Nicobar_Islands_ss[i]["active"])
        Andaman_and_Nicobar_Islands_confirmed.append(Andaman_and_Nicobar_Islands_ss[i]["confirmed"])
        Andaman_and_Nicobar_Islands_deceased.append(Andaman_and_Nicobar_Islands_ss[i]["deceased"])
        Andaman_and_Nicobar_Islands_recovered.append(Andaman_and_Nicobar_Islands_ss[i]["recovered"])
Andaman_and_Nicobar_Islands_act = sum(Andaman_and_Nicobar_Islands_active)
Andaman_and_Nicobar_Islands_con = sum(Andaman_and_Nicobar_Islands_confirmed)
Andaman_and_Nicobar_Islands_dec = sum(Andaman_and_Nicobar_Islands_deceased)
Andaman_and_Nicobar_Islands_rec = sum(Andaman_and_Nicobar_Islands_recovered)

Andhra_Pradesh = dicdis.loc[34]
Andhra_Pradesh_s = []
for ch in Andhra_Pradesh:
    if ch is not None:
        Andhra_Pradesh_s.append(ch)
Andhra_Pradesh_ss = df(r.json()["Andhra Pradesh"]["districtData"])
Andhra_Pradesh_active = []
Andhra_Pradesh_confirmed = []
Andhra_Pradesh_deceased = []
Andhra_Pradesh_recovered = []
for i in Andhra_Pradesh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Andhra_Pradesh_active.append(Andhra_Pradesh_ss[i]["active"])
        Andhra_Pradesh_confirmed.append(Andhra_Pradesh_ss[i]["confirmed"])
        Andhra_Pradesh_deceased.append(Andhra_Pradesh_ss[i]["deceased"])
        Andhra_Pradesh_recovered.append(Andhra_Pradesh_ss[i]["recovered"])
Andhra_Pradesh_act = sum(Andhra_Pradesh_active)
Andhra_Pradesh_con = sum(Andhra_Pradesh_confirmed)
Andhra_Pradesh_dec = sum(Andhra_Pradesh_deceased)
Andhra_Pradesh_rec = sum(Andhra_Pradesh_recovered)

Arunachal_Pradesh = dicdis.loc[35]
Arunachal_Pradesh_s = []
for ch in Arunachal_Pradesh:
    if ch is not None:
        Arunachal_Pradesh_s.append(ch)
Arunachal_Pradesh_ss = df(r.json()["Arunachal Pradesh"]["districtData"])
Arunachal_Pradesh_active = []
Arunachal_Pradesh_confirmed = []
Arunachal_Pradesh_deceased = []
Arunachal_Pradesh_recovered = []
for i in Arunachal_Pradesh_s:
    if (
            i == "Airport Quarantine" or i == "Unknown" or i == "Other State" or i == "Foreign Evacuees" or i == "Other Region" or i == "CAPF Personnel" or i == "Railway Quarantine"):
        continue
    else:
        Arunachal_Pradesh_active.append(Arunachal_Pradesh_ss[i]["active"])
        Arunachal_Pradesh_confirmed.append(Arunachal_Pradesh_ss[i]["confirmed"])
        Arunachal_Pradesh_deceased.append(Arunachal_Pradesh_ss[i]["deceased"])
        Arunachal_Pradesh_recovered.append(Arunachal_Pradesh_ss[i]["recovered"])
Arunachal_Pradesh_act = sum(Arunachal_Pradesh_active)
Arunachal_Pradesh_con = sum(Arunachal_Pradesh_confirmed)
Arunachal_Pradesh_dec = sum(Arunachal_Pradesh_deceased)
Arunachal_Pradesh_rec = sum(Arunachal_Pradesh_recovered)

"""**1 D LIST DISTRICT NAME'S**"""

plistdis = []
for i in listdis:
    col = []
    for j in i:
        if (
                j == "Airport Quarantine" or j == "Unknown" or j == "Other State" or j == "Foreign Evacuees" or j == "Other Region" or j == "CAPF Personnel" or j == "Railway Quarantine"):
            continue
        else:
            col.append(j)
        plistdis.append(col)
print(plistdis)

purelist = []

"""# **Calculating Longitude & Latitude** 
# **because json Doesnot Have location of each district.**

> Using Geopy python packages 

>json -[link text](https://api.covid19india.org/state_district_wise.json)
"""

"""**Maintain Orde**

# **APPENDING ALL STATEWISE DISTRICT NAMES TO ONE LIST**
"""

pureActive = []
pureConfirmed = []
puredeceased = []
purerecovered = []

"""# *APPENDING ALL CASES TO ONE LIST*"""

pureActive = assamactive + biharactive + Chandigarhactive + Chhattisgarhactive + Delhiactive + Dadra_and_Nagar_Haveli_and_Daman_and_Diu_active + Goa_active + Gujarat_active + Himachal_Pradesh_active + Haryana_active + Jharkhand_active + Jammu_and_Kashmir_active + Karnataka_active + Kerala_active + Ladakh_active + Lakshadweep_active + Maharashtra_active + Meghalaya_active + Manipur_active + Madhya_Pradesh_active + Mizoram_active + Nagaland_active + Odisha_active + Punjab_active + Puducherry_active + Rajasthan_active + Sikkim_active + Telangana_active + Tamil_Nadu_active + Tripura_active + Uttar_Pradesh_active + Uttarakhand_active + West_Bengal_active + Andaman_and_Nicobar_Islands_active + Andhra_Pradesh_active + Arunachal_Pradesh_active
pureConfirmed = assamconfirmed + biharconfirmed + Chandigarhconfirmed + Chhattisgarhconfirmed + Delhiconfirmed + Dadra_and_Nagar_Haveli_and_Daman_and_Diu_confirmed + Goa_confirmed + Gujarat_confirmed + Himachal_Pradesh_confirmed + Haryana_confirmed + Jharkhand_confirmed + Jammu_and_Kashmir_confirmed + Karnataka_confirmed + Kerala_confirmed + Ladakh_confirmed + Lakshadweep_confirmed + Maharashtra_confirmed + Meghalaya_confirmed + Manipur_confirmed + Madhya_Pradesh_confirmed + Mizoram_confirmed + Nagaland_confirmed + Odisha_confirmed + Punjab_confirmed + Puducherry_confirmed + Rajasthan_confirmed + Sikkim_confirmed + Telangana_confirmed + Tamil_Nadu_confirmed + Tripura_confirmed + Uttar_Pradesh_confirmed + Uttarakhand_confirmed + West_Bengal_confirmed + Andaman_and_Nicobar_Islands_confirmed + Andhra_Pradesh_confirmed + Arunachal_Pradesh_confirmed
puredeceased = assamdeceased + bihardeceased + Chandigarhdeceased + Chhattisgarhdeceased + Delhideceased + Dadra_and_Nagar_Haveli_and_Daman_and_Diu_deceased + Goa_deceased + Gujarat_deceased + Himachal_Pradesh_deceased + Haryana_deceased + Jharkhand_deceased + Jammu_and_Kashmir_deceased + Karnataka_deceased + Kerala_deceased + Ladakh_deceased + Lakshadweep_deceased + Maharashtra_deceased + Meghalaya_deceased + Manipur_deceased + Madhya_Pradesh_deceased + Mizoram_deceased + Nagaland_deceased + Odisha_deceased + Punjab_deceased + Puducherry_deceased + Rajasthan_deceased + Sikkim_deceased + Telangana_deceased + Tamil_Nadu_deceased + Tripura_deceased + Uttar_Pradesh_deceased + Uttarakhand_deceased + West_Bengal_deceased + Andaman_and_Nicobar_Islands_deceased + Andhra_Pradesh_deceased + Arunachal_Pradesh_deceased
purerecovered = assamrecovered + biharrecovered + Chandigarhrecovered + Chhattisgarhrecovered + Delhirecovered + Dadra_and_Nagar_Haveli_and_Daman_and_Diu_recovered + Goa_recovered + Gujarat_recovered + Himachal_Pradesh_recovered + Haryana_recovered + Jharkhand_recovered + Jammu_and_Kashmir_recovered + Karnataka_recovered + Kerala_recovered + Ladakh_recovered + Lakshadweep_recovered + Maharashtra_recovered + Meghalaya_recovered + Manipur_recovered + Madhya_Pradesh_recovered + Mizoram_recovered + Nagaland_recovered + Odisha_recovered + Punjab_recovered + Puducherry_recovered + Rajasthan_recovered + Sikkim_recovered + Telangana_recovered + Tamil_Nadu_recovered + Tripura_recovered + Uttar_Pradesh_recovered + Uttarakhand_recovered + West_Bengal_recovered + Andaman_and_Nicobar_Islands_recovered + Andhra_Pradesh_recovered + Arunachal_Pradesh_recovered

print(len(pureActive))
print(len(pureConfirmed))
print(len(puredeceased))
print(len(purerecovered))

"""# **Anding active ,confirmed,deceased,recovered cases to DataFrame**"""


d=pd.DataFrame(pd.read_csv("data.csv"))
print(d)
d["ACTIVE CASES"] = pureActive
d["CONFIRMED CASES"] = pureConfirmed
d["DECEASED CASES"] = puredeceased
d["RECOVERED CASES"] = purerecovered

d.at[0,'Latitude']=26.6935
d.at[0,'longitude']=91.5984
d.at[565,'Latitude']=11.6643
d.at[565,'longitude']=78.1460
d.at[133,'Latitude']=23.7337
d.at[133,'longitude']=69.8597
d.at[68,'Latitude']=23.7337
d.at[68,'longitude']=69.8597
d.at[709,'Latitude']=14.4426
d.at[709,'longitude']=79.9865
d.at[226,'Latitude']=32.5530
d.at[226,'longitude']=75.1108
d.at[468,'Latitude']=11.7003
d.at[468,'longitude']=75.5425
d.at[135,'Latitude']=23.5880
d.at[135,'longitude']=72.3693

d.at[160,'Latitude']=31.4685
d.at[160,'longitude']=76.2708

d.at[235,'Latitude']=17.9104
d.at[235,'longitude']=77.5199

d.at[144,'Latitude']=21.1702
d.at[144,'longitude']=72.8311

d.at[150,'Latitude']=32.5534
d.at[150,'longitude']=76.1258


d.at[409,'Latitude']=26.8038
d.at[409,'longitude']=94.9767


d.at[126,'Latitude']=20.8254
d.at[126,'longitude']=73.7007

d.at[601,'Latitude']=25.4520
d.at[601,'longitude']=80.5438

d.at[658,'Latitude']=27.2716
d.at[658,'longitude']=82.8210

print(d)
d.drop(index=[168,489,486,403],inplace=True)

print(d[d.longitude==0].index)
d.drop(d[d.longitude==0].index,inplace=True)


# you can drop this district because geopy is not able to find lon & data or update


"""# **Writing Files to Google Drive**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

# Commented out IPython magic to ensure Python compatibility.
# %cd grive/My\ Drive/

"""# Plz edit the path to your Drive or create a folder covid_csv"""

d.to_csv('coviddata.csv')
